name: macOS Build

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main

  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    name: 🚧 macOS
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 'Install Ninja'
      run: brew install ninja

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.7.1'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        modules: 'qtconnectivity qthttpserver qtimageformats qtmultimedia'
        archives: 'qttranslations qttools qtsvg qtbase'

# TODO: Can we build TagLib and use it here?
    - name: '🚧 Build Cantata'
      run: |
        cmake -S. -G Ninja -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        cmake --build build

    - name: '📦 Package Cantata'
      run: cpack -G DragNDrop -B package --config build/CPackConfig.cmake

    - name: '⏫ Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: macos-dmg
        path: package/*.dmg
        if-no-files-found: error
