name: Windows Build

on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟨', sys: ucrt64  }
          - { icon: '🟧', sys: clang64 }
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          ninja:p
          taglib:p
          qt6-tools:p
          qt6-base:p
          qt6-svg:p
          qt6-multimedia:p
          qt6-httpserver:p
          ffmpeg:p
          libebur128:p
          mpg123:p
          qt6-imageformats:p

    - name: '🚧 Build Cantata'
      run: |
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build build

    - name: '📦 Package Cantata'
      run: cmake --install build --prefix $PWD/package

    - name: '⏫ Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: windows-standalone-${{ matrix.sys }}
        path: package/
        if-no-files-found: error
